# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8a02c709cbb6126f973d27f396029bf"
name = "image-process"
handle = "image-process"
application_url = "https://packages-gmbh-currently-adopted.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-20612a7e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,read_inventory,write_discounts,write_customers"

[auth]
redirect_urls = [
  "https://packages-gmbh-currently-adopted.trycloudflare.com/auth/callback",
  "https://packages-gmbh-currently-adopted.trycloudflare.com/auth/shopify/callback",
  "https://packages-gmbh-currently-adopted.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
